version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jpa_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - "6033:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jpa_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      TOKEN_API_KEY: sprgboot
      TOKEN_PALABRA_SECRETA: gihub
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  db-data: