version: '3.8'

services:

  app:
    image: aurora-app:test-dbh2-v1
    container_name: aurora-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:jpa_db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      TOKEN_API_KEY: sprgboot
      TOKEN_PALABRA_SECRETA: github
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - /ruta/local/a/data:/data