###
POST http://localhost:8000/registrarse
Content-Type: application/json

{
  "username": "josePruebaRegistro2",
  "correo": "josePrueba@example.com",
  "password": "jose"
}

<> 2024-06-19T144822.200.txt
###
POST http://localhost:8000/registrarse
Content-Type: application/json

{
  "username": "regular_user",
  "correo": "user@example.com",
  "password": "123"
}

<> 2024-06-19T144822-1.200.txt
###
POST http://localhost:8000/registrarse
Content-Type: application/json

{
  "username": "guest_user",
  "correo": "guest@example.com",
  "password": "guest_pass"
}

<> 2024-06-19T144822-2.200.txt
###
POST http://localhost:8000/registrarse
Content-Type: application/json

{
  "username": "mod_user",
  "correo": "mod@example.com",
  "password": "mod_pass"
}

<> 2024-06-19T144823.200.txt
###
POST http://localhost:8000/registrarse
Content-Type: application/json

{
  "username": "manager_user",
  "correo": "manager@example.com",
  "password": "manager_pass"
}

<> 2024-06-19T144823-1.200.txt

###
POST http://localhost:8000/iniciar
Content-Type: application/json

{
  "username": "regular_user",
  "password": "user_pass"
}