# TEST Controlado de cliente
# Protegido

### /iniciar
POST http://localhost:8081/iniciar
Content-Type: application/json

{
  "username": "jose2",
  "password": "456",
  "token": "my-secret-token"
}
> {% client.global.set("auth_token", response.body.token); %}


### /crear
POST http://localhost:8081/clientes/crear
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "firstname": "",
  "middlename": "",
  "lastname": "",
  "birthday": "",
  "email": "",
  "mobile": "",
  "homephone": "",
  "nationality": ""
}

### /actualizar/{id}
### Se debe proporcionar ID en el path
PUT http://localhost:8081/clientes/actualizar/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "firstname": "",
  "middlename": "",
  "lastname": "",
  "birthday": "",
  "createDate": "",
  "email": "",
  "mobile": "",
  "homephone": "",
  "nationality": "",
  "secCodeId": ""
}

### /eliminar
POST http://localhost:8081/clientes/eliminar
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "clienteid":2
}


### /findbyId
GET http://localhost:8081/clientes/findby-Id/1
Authorization: Bearer {{auth_token}}

### /findby-nombre
GET http://localhost:8081/clientes/findby-nombre/John
Authorization: Bearer {{auth_token}}

###/findby-estado
GET http://localhost:8081/clientes/findby-estado/false
Authorization: Bearer {{auth_token}}